# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Patissier' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Patissier

use_frameworks!

pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod "UILoadControl"

pod 'Alamofire', '~> 4.4'

pod 'IQKeyboardManagerSwift'

end
